# Usa uma imagem leve do Nginx
FROM nginx:alpine

# Remove arquivos padrão do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos do seu frontend para a pasta do nginx
COPY frontend/ /usr/share/nginx/html

EXPOSE 80
