FROM node:22-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependência para instalar os pacotes
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o código fonte (pasta src) para dentro do container
COPY src/ ./src

# Expõe a porta que sua aplicação vai usar
EXPOSE 8000

# Comando para iniciar o servidor
CMD ["node", "src/server.js"]
